import { cn } from "@/lib/utils";
import { client } from "@/shared/client";
import QueryProvider from "@/shared/providers/query-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import "./index.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    const token = (await cookies()).get("token")?.value;

    client.setConfig({
        auth: token,
    });

    return (
        <html
            lang="en"
            className={cn("font-sans antialiased", "font-sans", inter.variable)}
        >
            <body>
                <QueryProvider>{children}</QueryProvider>
            </body>
        </html>
    );
};

export default RootLayout;
